apiVersion: v1
kind : Secret
metadata:
  name: mysql-secret
  namespace: polling
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: <Replace Me>  
  MYSQL_DATABASE: <Replace Me>
  MYSQL_USER: <Replace Me>
  MYSQL_PASSWORD: <Replace Me>

