apiVersion: v1
kind : Secret
metadata:
  name: mysql-secret
  namespace: polling
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root  
  MYSQL_DATABASE: polling-app
  MYSQL_USER: callicoder
  MYSQL_PASSWORD: callicoder

